# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True)),
                ('contractStarted', models.DateTimeField(blank=True)),
                ('country', models.CharField(max_length=150)),
                ('nationalId', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=150)),
                ('event', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=150)),
                ('serialNUmber', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesDetails', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True)),
                ('total', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('nationalId', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('dateInserted', models.DateTimeField(blank=True)),
                ('contractStarted', models.DateTimeField(blank=True)),
                ('country', models.CharField(max_length=150)),
                ('nationalId', models.CharField(max_length=150)),
                ('typeAccess', models.CharField(max_length=150)),
            ],
        ),
    ]
